apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inclusion
  description: Emoji Inclusion App
  tags:
  - java
  - spring
  - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=inclusion'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
